apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  replicas: 2
  revisionHistoryLimit: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: deploy
  template:
    metadata:
      labels:
        app: deploy
        environment: dev
        tier: backend
        department: engineering
      annotations:
        kubernetes.io/change-cause: "tsola2002/node-microservices:latest"
    spec:
      containers:
      - name: deploy
        image: tsola2002/node-microservices:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
