apiVersion: apps/v1
kind: Deployment
metadata:
  name: bootstrap
spec:
  selector:
    matchLabels:
      app: bootstrap
  template:
    metadata:
      labels:
        app: bootstrap
    spec:
      containers:
      - name: bootstrap
        image: tsola2002/omatsola-repo:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
