apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dashboard-deploy
  template:
    metadata:
      labels:
        app: dashboard-deploy
      annotations:
        kubernetes.io/change-cause: "version 3 changed to tsola2002/omatsola-repo:v3"
    spec:
      containers:
      - name: dashboard-deploy
        image: tsola2002/omatsola-repo:v3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
