apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: personal
  template:
    metadata:
      labels:
        app: personal
      annotations:
        kubernetes.io/change-cause: "tsola2002/kube-image-v2"
    spec:
      containers:
      - name: personal
        image: tsola2002/kube-image-v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
