apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: personal
  template:
    metadata:
      labels:
        app: personal
      annotations:
        kubernetes.io/change-cause: "version 4 changed to tsola2002/omatsola-repo:v3"
    spec:
      containers:
      - name: personal
        image: tsola2002/omatsola-repo:v3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
