apiVersion: v1
kind: Pod
metadata:
  name: personal
  labels:
    name: personal
spec:
  containers:
  - name: personal
    image: tsola2002/omatsola-repo:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"    
    ports:
      - containerPort: 80
