apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret
spec:
  selector:
    matchLabels:
      app: secret
  template:
    metadata:
      labels:
        app: secret
    spec:
      
      containers:
      - name: secrets
        image: busybox
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

