apiVersion: v1
kind: ConfigMap
metadata:
  name: app-properties
data:
  app-name: order
  app-version: 1.0.0
  team: engineering


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf: |
    server {
      listen 80;

      location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
          try_files $uri $uri/ /index.html;
      }

      error_page   500 502 503 504  /50x.html;

      location = /50x.html {
          root   /usr/share/nginx/html;
      }

      location /api/ {
          proxy_pass http://customer;

          proxy_set_header Host            $host;
          proxy_set_header X-Forwarded-For $remote_addr;
          proxy_set_header X-Request-Id    $request_id;
      }
    }


---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-map
spec:
  selector:
    matchLabels:
      app: config-map
  template:
    metadata:
      labels:
        app: config-map
    spec:
      containers:
      - name: config-map-env
        image: busybox
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        command:
          - "/bin/sh"
          - "-c"
        args:
          - "env && sleep 3600"
        env:
          - name: APP_VERSION
            valueFrom:
              configMapKeyRef:
                name: app-properties
                key: app-version
          - name: APP_NAME
            valueFrom:
              configMapKeyRef:
                name: app-properties
                key: app-name
          - name: TEAM
            valueFrom:
              configMapKeyRef:
                name: app-properties
                key: team


